<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="stereo">
    <xacro:include filename="dimensions.xacro"/>

    <!-- world -->
    <link name="world"></link>

    <!-- Sensor body -->
    <link name="body">
        <collision>
            <geometry>
                <box size="${body_dim}"/>
            </geometry>
        </collision>

        <visual>
            <geometry>
                <box size="${body_dim}"/>
            </geometry>
        </visual>

        <inertial>
            <mass value="1"/>
            <inertia ixx="1"  ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
        </inertial>

    </link>

    <joint name="body_fix" type="fixed">
        <origin xyz="0 0 ${0.5*body_z}"/>
        <parent link="world"/>
        <child link="body"/>
    </joint>

    <!-- testing rod -->
    <link name="rod">
        <collision>
            <origin xyz="${rod_r} 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <box size="${2*rod_r} ${2*rod_r} ${rod_len}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="${rod_r} 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <box size="${2*rod_r} ${2*rod_r} ${rod_len}"/>
            </geometry>
        </visual>

        <inertial>
            <mass value="1"/>
            <inertia ixx="1"  ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
        </inertial>

    </link>

    <joint name="rod_body" type="revolute">
        <origin xyz="${body_x/2} 0 0" rpy="0 0 0"/>
        <parent link="body"/>
        <child link="rod"/>
        <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/>
        <axis xyz="1 0 0"/>
    </joint>

    <xacro:include filename="gazebo.xacro"/>
</robot>