<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chaser">
    <xacro:include filename="dimensions.xacro"/>
    <xacro:include filename="macros.xacro"/>
    
    <!-- Dummy root link -->
    <!-- <link name="root"></link> -->

    <!-- Body -->
    <link name="body">
        <collision name="body_col">
            <geometry><box size="${body_x} ${body_y} ${body_z + leg_len}"/>
            </geometry>
        </collision>

        <collision name="head_col">
            <origin xyz="0 0 ${body_z/2 + head_len/2}"/>
            <geometry>
                <cylinder radius="${head_r}" length="${head_len}"/>
            </geometry>
        </collision>

        <visual name="body_vis">
            <geometry>
                <box size="${body_dim}"/>
            </geometry>

        </visual>

        <visual name="leg_1">
            <origin xyz="${body_x/2 - leg_r} ${body_y/2 - leg_r} ${-body_z}"/>
            <geometry>
                <cylinder radius="${leg_r}" length="${leg_len}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <visual name="leg_2">
            <origin xyz="${-body_x/2 + leg_r} ${body_y/2 - leg_r} ${-body_z}"/>
            <geometry>
                <cylinder radius="${leg_r}" length="${leg_len}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <visual name="leg_3">
            <origin xyz="${body_x/2 - leg_r} ${-body_y/2 + leg_r} ${-body_z}"/>
            <geometry>
                <cylinder radius="${leg_r}" length="${leg_len}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <visual name="leg_4">
            <origin xyz="${-body_x/2 + leg_r} ${-body_y/2 + leg_r} ${-body_z}"/>
            <geometry>
                <cylinder radius="${leg_r}" length="${leg_len}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <visual name="head_vis">
            <origin xyz="0 0 ${body_z/2 + head_len/2}"/>
            <geometry>
                <cylinder radius="${head_r}" length="${head_len}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <xacro:inertial_box mass="30.0" x="${body_x}" y="${body_y}" z="${body_z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- <joint name="root_fix" type="fixed">
        <origin xyz="0 0 0"/>
        <parent link="root"/>
        <child link="body"/>
    </joint> -->

    <!-- Camera -->
    <link name="camera">
        <visual>
            <origin xyz="${cam_size/2} 0 0"/>
            <geometry>
                <box size="${cam_size} ${cam_size} ${cam_size}"/>
            </geometry>

            <material name="red"/>
        </visual>

    </link>

    <joint name="camera_fix" type="fixed">
        <origin xyz = "${head_r} 0 ${(head_len + body_z) / 2}"/>
        <parent link = "body"/>
        <child link = "camera"/>
    </joint>

    <link name="camera_optical"></link>
    
    <joint name="camera_optical_joint" type="fixed">
        <!-- these values have to be these values otherwise the gazebo camera
            image won't be aligned properly with the frame it is supposedly
            originating from -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera"/>
        <child link="camera_optical"/>
    </joint>

    <!-- Grabber -->
    <link name="grabber">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="${0.35 - body_x/2}"/>
            </geometry>

            <material name="black"/>
        </visual>
        <visual>
            <origin xyz="0 0 ${-(0.35 - body_x/2)/2}"/>
            <geometry>
                <sphere radius="0.02"/>
            </geometry>
        </visual>
    </link>

    <joint name="grabber_fix" type="fixed">
        <origin xyz="${body_x/2} 0 0" rpy="0 ${-pi/2} 0"/>
        <parent link="body"/>
        <child link="grabber"/>

    </joint>
    
    <xacro:include filename="gazebo.xacro"/>
</robot>