<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Body --> 
    <xacro:property name="U" value="0.1"/>
    <xacro:property name="cube_x" value="1"/>
    <xacro:property name="cube_y" value="1"/>
    <xacro:property name="cube_z" value="2"/>
    <xacro:property name="cube_dim" value="${cube_x * U} ${cube_y * U} ${cube_z * U}"/>

    <!-- Flaps --> 
    <xacro:property name="arm" value="${U}"/>
    <xacro:property name="panel_z" value="0.01"/>
    <xacro:property name="panel_x" value="0.1"/>
    <xacro:property name="panel_y" value="0.3"/>
    <xacro:property name="panel_dim" value="${panel_x} ${panel_y} ${panel_z}"/>

</robot>