<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Body --> 
    <xacro:property name="body_x" value="0.15"/>
    <xacro:property name="body_y" value="${body_x}"/>
    <xacro:property name="body_z" value="1.5"/>
    <xacro:property name="body_dim" value="${body_x} ${body_y} ${body_z}"/>

    <!-- Arm -->
    <xacro:property name="arm_thickness" value="0.15"/>
    <xacro:property name="arm_span" value="0.5"/>
    <xacro:property name="arm_length" value="1.25"/>
    <xacro:property name="arm_coll_dim" value="${arm_length} ${arm_span} ${arm_thickness}"/>
    <xacro:property name="arm_vis1_dim" value="${arm_length-arm_thickness} ${arm_thickness} ${arm_thickness}"/>
    <xacro:property name="arm_vis2_dim" value="${arm_thickness} ${arm_span} ${arm_thickness}"/>

    <!-- Cameras -->
    <!-- <xacro:property name="ipd" value="${64.0 * 0.01}"/> -->
    <xacro:property name="ipd" value="0.5"/>
    <xacro:property name="cam_size" value="0.05"/>

</robot>